###3
POST http://localhost:8081/api/pois
Content-Type: application/json

{
  "stopId": "place-dwnxg",
  "stopName": "Downtown Crossing",
  "name": "Boston Common",
  "category": "park",
  "distanceMeters": 250,
  "isOpenNow": true
}

###3
GET http://localhost:8081/api/pois
Content-Type: application/json